config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  namespace :admin do
    resources :photos
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

	has_attached_file :image,
		:storage => :dropbox,
		:dropbox_credentials => { :app_key => "54gkoolq3sdnhpf",
			:app_secret => "ht6cgyn9h7e9qp1",
			:access_token => "3lmngnb1k4mgcdmo",
			:access_token_secret => "k2tzv1zfhhfdnar",
			:user_id => "93851919",
			:access_type => "app_folder"},
			:dropbox_visibility => 'public',
			:dropbox_options => {environment: ENV["RACK_ENV"]}
	validates_with AttachmentPresenceValidator, :attributes => :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	acts_as_taggable

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	validates :name, uniqueness: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
  	@photo = Photo.new(photo_params)
    params[:photo][:tag_list].each do |tag|
      @photo.tag_list.add(tag.downcase) if tag.present?
    end
    if params[:photo][:new_tags].present?
      new_tags = params[:photo][:new_tags].split(',')
      new_tags.each do |new_tag|
        @photo.tag_list.add(new_tag)
      end
    end
		if @photo.save
			redirect_to admin_photos_path, notice: "photoed"
		else
      flash[:alert] = "choose a photo"
			render :new
		end
  end

  def destroy
    Photo.destroy(params[:id]) if params[:id]
    redirect_to admin_photos_path, notice: "deleted"
  end

  def photo_params
    params.require(:photo).permit(:image, :title, :tag_list, :new_tags)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  	@photo = Photo.new
  	@photos = Photo.all
  end

  def create
  	@photo = Photo.new(photo_params)
		if @photo.save
			redirect_to photos_path, notice: "photoed"
		else
			redirect_to photos_path, notice: "error"
		end
  end

  def destroy
    Photo.destroy(params[:id]) if params[:id]
    redirect_to photos_path, notice: "deleted"
  end

  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/photos/index.html.erb
<body>
  <div class="spinner"></div> 
    <div class="bg-content">
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= button_to 'Add a New Photo', new_admin_photo_path, :class => 'btn btn-primary btn-lg', :method => :get%> 
						<h3>List of Photos</h3>
						<% @photos.each do |photo|%>
							<%= image_tag(photo.image.url)%>
							<br>
							<div id="photo-options">
								<%= link_to photo.tag_list,'', :class => 'btn btn-success btn-lg'%>
								<%= button_to 'delete', admin_photo_path(photo), :confirm => 'Are you sure?', :class => 'btn btn-primary btn-lg', :method => :delete%>
							</div>
						<% end%>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/admin/photos/new.html.erb
<body>
  <div class="spinner"></div> 
    <div class="bg-content">
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= button_to 'Photo List', admin_photos_path, :class => 'btn btn-primary btn-lg', :method => :get%>						
						<h3>Add a new Photo</h3>
						<%= form_for [:admin, @photo] do |form|%>
							<%= form.label :title%>
							<%= form.text_field :title%>
							<%= form.label :image%>
							<%= form.file_field :image%>
							<%= form.label :tags%>
							<%= form.select :tag_list, options_for_select(Tag.all.collect{|item| [item.name, item.name]}), {}, {:multiple => true, :class => "chzn-select"}%></br>
							<%= form.label :new_tags%>
							<%= form.text_field :new_tags%></br>
							Note: type new tags with comma separate</br>
							<%= form.submit 'Submit', class: 'btn btn-primary btn-lg' %>
						<% end%>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	<title>About</title>
	<meta charset="utf-8">
	
	<meta name="description" content="Your description">
	<meta name="keywords" content="Your keywords">
	<meta name="author" content="Your name">
	

	<!--[if lt IE 8]>
  		<div style='text-align:center'><a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com//assets/upgrade.jpg"border="0"alt=""/></a></div>  
 	<![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!-->
	<!--<![endif]-->
	<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <link rel="stylesheet" href="css/docs.css" type="text/css" media="screen">
    <link rel="stylesheet" href="css/ie.css" type="text/css" media="screen">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400' rel='stylesheet' type='text/css'>
  <![endif]-->
	</head>

	<body>
    <div class="spinner"></div> 
      <div class="bg-content">
        <div class="container">
          <div class="row">
            <div class="span12"> 
              <!--============================== slider =================================-->
              <div class="flexslider">
                <ul class="slides">
                  <li> <img src="/assets/image-blank.png" alt="" > </li>
                  <li> <img src="/assets/image-blank.png" alt="" > </li>
                  <li> <img src="/assets/image-blank.png" alt="" > </li>
                  <li> <img src="/assets/image-blank.png" alt="" > </li>
                  <li> <img src="/assets/image-blank.png" alt="" > </li>
                </ul>
              </div>
              <span id="responsiveFlag"></span>
              <div class="block-slogan">
                <h2>Welcome!</h2>
                <div>
                  <p><a href="http://blog.templatemonster.com/free-website-templates/ " target="_blank" class="link-1">Click here</a> for more info about this free website template created by TemplateMonster.com. This is a Bootstrap template that goes with several layout options (for desktop, tablet, smartphone landscape and portrait) to fit all popular screen resolutions. The PSD source files of this template are available for free for the registered members of TemplateMonster.com. Feel free to get them!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      
        <!--============================== content =================================-->
      
        <div id="content" class="content-extra"><div class="ic"></div>
        <div class="row-1">
          <div class="container">
            <div class="row">
              <ul class="thumbnails thumbnails-1">
                <li class="span3">
                  <div class="thumbnail thumbnail-1">
                    <h3>Fashion</h3>
                    <img  src="/assets/page1-img1.jpg" alt="">
                    <section>
                      <strong>At vero eos et accusamus et iusto </strong>
                      <p>Odio dignissimos ducimus qui blanditiis praesentium voluptatum.</p>
                      <a href="#" class="btn btn-1">Read More</a>
                    </section>
                  </div>
                </li>
                <li class="span3">
                  <div class="thumbnail thumbnail-1">
                    <h3>Nature</h3>
                    <img  src="/assets/page1-img2.jpg" alt="">
                    <section>
                      <strong>Deleniti atque corrupti quos</strong>
                      <p>Dolores et quas molestias excepturi sint occaecati cupiditate non provident.</p>
                      <a href="#" class="btn btn-1">Read More</a>
                    </section>
                  </div>
                </li>
                <li class="span3">
                  <div class="thumbnail thumbnail-1">
                    <h3>Love story</h3>
                    <img  src="/assets/page1-img3.jpg" alt="">
                    <section>
                      <strong>Similique sunt in culpa qui officia </strong>
                      <p>Deserunt mollitia animi, id est laborum et dolorum fuga.</p>
                      <a href="#" class="btn btn-1">Read More</a>
                    </section>
                  </div>
                </li>
                <li class="span3">
                  <div class="thumbnail thumbnail-1">
                    <h3 class="title-1 extra">Fine art</h3>
                    <img  src="/assets/page1-img4.jpg" alt="">
                    <section>
                      <strong>Similique sunt in culpa qui officia</strong>
                      <p>Deserunt mollitia animi, id est laborum et dolorum fuga.</p>
                      <a href="#" class="btn btn-1">Read More</a>
                    </section>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <article class="span6">
              <h3>Shortly about me</h3>
              <div class="wrapper">
                <figure class="img-indent"><img src="/assets/page1-img5.jpg " alt="" /></figure>
                <div class="inner-1 overflow extra">
                  <div class="txt-1">Sed ut perspictis unde omnis natus error volupatem accusantium doloue laudantium, totam rem.</div>
                  Aperiam, eaque ipsa quae ab illo  veritatis et beatae vitae dicta sunt explicabo nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed
                  <div class="border-horiz"></div>
                  <div class="overflow">
                    <ul class="list list-pad">
                      <li><a href="#">Campaigns</a></li>
                      <li><a href="#">Portraits</a></li>
                      <li><a href="#">Fashion</a></li>
                      <li><a href="#">Fine Art</a></li>
                    </ul>
                    <ul class="list">
                      <li><a href="#">Advertising</a></li>
                      <li><a href="#">Lifestyle</a></li>
                      <li><a href="#">Love story</a></li>
                      <li><a href="#">Landscapes</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </article>
            <article class="span6">
              <h3>Latest photoshoots</h3>
              <ul class="list-photo">
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img6.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img7.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img8.jpg " alt="" /></a></li>
                <li class="last"><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img9.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img10.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img11.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img12.jpg " alt="" /></a></li>
                <li class="last"><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img13.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img14.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img15.jpg " alt="" /></a></li>
                <li><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img16.jpg " alt="" /></a></li>
                <li class="last"><a href="/assets/image-blank.png" class="magnifier" ><img src="/assets/page1-img17.jpg " alt="" /></a></li>
              </ul>
            </article>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" href="/assets/favicon.ico" type="image/x-icon">
	<link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="/assets/bootstrap.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/assets/responsive.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/assets/style.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/assets/touchTouch.css" type="text/css" media="screen">
	<link rel="stylesheet" href="/assets/kwicks-slider.css" type="text/css" media="screen">
	<link rel='stylesheet' href="/assets/google_apis_fonts.css" type='text/css'>
	<script type="text/javascript" src="/assets/jquery.js"></script>
  <script type="text/javascript" src="/assets/superfish.js"></script>
	<script type="text/javascript" src="/assets/jquery.flexslider-min.js"></script>
	<script type="text/javascript" src="/assets/jquery.kwicks-1.5.1.js"></script>
	<script type="text/javascript" src="/assets/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="/assets/jquery.cookie.js"></script>    
	<script type="text/javascript" src="/assets/touchTouch.jquery.js"></script>
	<script type="text/javascript">if($(window).width()>1024){document.write("<"+"script src='/assets/jquery.preloader.js'></"+"script>");}	</script>
	
	<script>		
		 jQuery(window).load(function() {	
		 $x = $(window).width();		
	if($x > 1024)
	{			
	jQuery("#content .row").preloader();    }	
		 
     jQuery('.magnifier').touchTouch();			
    jQuery('.spinner').animate({'opacity':0},1000,'easeOutCubic',function (){jQuery(this).css('display','none')});	
  		  }); 
				
	</script>
</head>
<body>
	<!--============================== header =================================-->
	<header>
    <div class="container clearfix">
    	<div class="row">
        <div class="span12">
        	<div class="navbar navbar_">
            <div class="container">
            	<h1 class="brand brand_"><a href="index.html"><img alt="" src="/assets/logo.gif"> </a></h1>
            	<a class="btn btn-navbar btn-navbar_" data-toggle="collapse" data-target=".nav-collapse_">Menu <span class="icon-bar"></span> </a>
            	<div class="nav-collapse nav-collapse_  collapse">
                <ul class="nav sf-menu">
                	<li class="active"><a href="index.html">About</a></li>
                	<li class="sub-menu"><a href="index-1.html">Services</a>
                    <ul>
                    	<li><a href="#">Dolore </a></li>
                    	<li><a href="#">Consecte</a></li>
                    	<li><a href="#">Conseq</a></li>
                  	</ul>
                  </li>
	                <li><a href="index-2.html">Folio</a></li>
	                <li><a href="index-3.html">Blog</a></li>
	                <li><a href="index-4.html">Contact</a></li>
	              </ul>
              </div>
          	</div>
          </div>
      	</div>
      </div>
 		</div>
  </header>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
	<%= yield %>
	
	<!--============================== footer =================================-->
		<footer>
      <div class="container clearfix">
    		<ul class="list-social pull-right">
          <li><a class="icon-1" href="#"></a></li>
          <li><a class="icon-2" href="#"></a></li>
          <li><a class="icon-3" href="#"></a></li>
          <li><a class="icon-4" href="#"></a></li>
        </ul>
    		<div class="privacy pull-left">Website Owned by <a href="http://www.facebook.com/anildias" target="_blank" rel="nofollow">Dias Davis</a></div>
  		</div>
    </footer>
	
</body>
</html>

app/views/photos/index.html.erb
<head>
	<%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</head>
<h1>Submit a new Post</h1>
<%= form_for @photo do |form|%>
	<%= form.label :title%>
	<%= form.text_field :title%>
	<%= form.label :image%>
	<%= form.file_field :image%>
	<%= form.submit 'Submit', class: 'btn btn-primary btn-lg' %>
<% end%>
<h1>List of Posts</h1>
<% @photos.each do |photo|%>
	<%= photo.title%>
	<%= photo.image.url%>
	<%= button_to 'delete', photo_path(photo), :confirm => 'Are you sure?', :method => :delete%>
	<div>
		<%= image_tag(photo.image.url)%>
	</div>
<% end%>